#!/bin/bash

os=($(uname -s))
baudrate=115200

case "$os" in
    Linux*)
        serialPort=$1
        if [[ $serialPort -eq "" ]]; then
            serialPort="0"
        fi

        screen /dev/ttyUSB$serialPort $baudrate
        ;;
    Darwin*)
        screen /dev/tty.SLAB_USBtoUART $baudrate
        ;;
esac




i
